STATUS_OK = "200"
STATUS_ERROR = "500"

HOST = "localhost"
PORT = "7000"

REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

MODEL_PATH = './view/model/frozen_inference_graph.pb'
OBJECT_THRESHOLD = 0.85
OBJECT_CLASSES = [1]
FRAMES_TO_LIVE = 5
TIME_TO_LIVE = 10
ALERT_DELAY = 5.0
